name: Render Spring POC hook

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          tasks: build
          java-home: ${{ env.JAVA_HOME }}
          publish-atoms: false

      - name: Trigger Render deploy hook
        run: curl -X POST -d '{}' https://api.render.com/deploy/srv-coilasf79t8c738j2pv0?key=qUGjTS3Bnqo
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
